// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRelationnelle.Models;

namespace RRelationnelle.Migrations
{
    [DbContext(typeof(RrelationnelApiContext))]
    [Migration("20230117204248_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RessourcesRelationelles.Class.Admin", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("_activation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("_creationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_fName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_lName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_User");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("RessourcesRelationelles.Class.Category", b =>
                {
                    b.Property<int>("Id_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("_creationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idcreator")
                        .HasColumnType("int");

                    b.HasKey("Id_Category");

                    b.HasIndex("idcreator");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("RessourcesRelationelles.Class.Ressource", b =>
                {
                    b.Property<int>("ID_Ressource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("_activation")
                        .HasColumnType("bit");

                    b.Property<int>("_category")
                        .HasColumnType("int");

                    b.Property<string>("_content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("_creationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_views")
                        .HasColumnType("int");

                    b.HasKey("ID_Ressource");

                    b.HasIndex("_category");

                    b.ToTable("Ressource");
                });

            modelBuilder.Entity("RessourcesRelationelles.Class.Category", b =>
                {
                    b.HasOne("RessourcesRelationelles.Class.Admin", "Creator")
                        .WithMany()
                        .HasForeignKey("idcreator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("RessourcesRelationelles.Class.Ressource", b =>
                {
                    b.HasOne("RessourcesRelationelles.Class.Category", "Id_Category")
                        .WithMany()
                        .HasForeignKey("_category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Id_Category");
                });
#pragma warning restore 612, 618
        }
    }
}
