name: Generate and publish API Client

on:
  push:
    branches:
      - [ "main", "Develop" ]

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.*

      # Serving app
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Entity Framework App
        run: dotnet build --configuration Release

      - name: Serve app
        run: dotnet run --project RRelationnelle/APIRRelationnel.csproj &

      # Client generation
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: '18.15.0'

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Setup java for openapi-generator-cli
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Download spec
        run: wget https://localhost:5001/swagger/v1/swagger.json --no-check-certificate --output-document spec.json

      - name: Generate TypeScript Client
        run: openapi-generator-cli generate -g typescript-axios -i spec.json -o cubes-api-client --additional-properties=npmName=cubes-api-client,supportsES6=true,withoutPrefixEnums=true,npmVersion=$(npm view cubes-api-client version),withInterfaces=true

      - name: Install tsc
        run: npm install -g typescript

      - name: Publish Client Package
        run: cd cubes-api-client && npm i && npm version patch && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
